// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: proto/icon/lightclient/v1/light.proto

package icon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrustingPeriod uint64 `protobuf:"varint,1,opt,name=trusting_period,json=trustingPeriod,proto3" json:"trusting_period,omitempty"`
	FrozenHeight   uint64 `protobuf:"varint,2,opt,name=frozen_height,json=frozenHeight,proto3" json:"frozen_height,omitempty"`
	MaxClockDrift  uint64 `protobuf:"varint,3,opt,name=max_clock_drift,json=maxClockDrift,proto3" json:"max_clock_drift,omitempty"`
	LatestHeight   uint64 `protobuf:"varint,4,opt,name=latest_height,json=latestHeight,proto3" json:"latest_height,omitempty"`
	SrcNetworkId   string `protobuf:"bytes,5,opt,name=src_network_id,json=srcNetworkId,proto3" json:"src_network_id,omitempty"`
	NetworkId      uint64 `protobuf:"varint,6,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	NetworkTypeId  uint64 `protobuf:"varint,7,opt,name=network_type_id,json=networkTypeId,proto3" json:"network_type_id,omitempty"`
}

func (x *ClientState) Reset() {
	*x = ClientState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_icon_lightclient_v1_light_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientState) ProtoMessage() {}

func (x *ClientState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_icon_lightclient_v1_light_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientState.ProtoReflect.Descriptor instead.
func (*ClientState) Descriptor() ([]byte, []int) {
	return file_proto_icon_lightclient_v1_light_proto_rawDescGZIP(), []int{0}
}

func (x *ClientState) GetTrustingPeriod() uint64 {
	if x != nil {
		return x.TrustingPeriod
	}
	return 0
}

func (x *ClientState) GetFrozenHeight() uint64 {
	if x != nil {
		return x.FrozenHeight
	}
	return 0
}

func (x *ClientState) GetMaxClockDrift() uint64 {
	if x != nil {
		return x.MaxClockDrift
	}
	return 0
}

func (x *ClientState) GetLatestHeight() uint64 {
	if x != nil {
		return x.LatestHeight
	}
	return 0
}

func (x *ClientState) GetSrcNetworkId() string {
	if x != nil {
		return x.SrcNetworkId
	}
	return ""
}

func (x *ClientState) GetNetworkId() uint64 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *ClientState) GetNetworkTypeId() uint64 {
	if x != nil {
		return x.NetworkTypeId
	}
	return 0
}

type ConsensusState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageRoot          []byte `protobuf:"bytes,1,opt,name=message_root,json=messageRoot,proto3" json:"message_root,omitempty"`
	NextProofContextHash []byte `protobuf:"bytes,2,opt,name=next_proof_context_hash,json=nextProofContextHash,proto3" json:"next_proof_context_hash,omitempty"`
}

func (x *ConsensusState) Reset() {
	*x = ConsensusState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_icon_lightclient_v1_light_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsensusState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusState) ProtoMessage() {}

func (x *ConsensusState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_icon_lightclient_v1_light_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusState.ProtoReflect.Descriptor instead.
func (*ConsensusState) Descriptor() ([]byte, []int) {
	return file_proto_icon_lightclient_v1_light_proto_rawDescGZIP(), []int{1}
}

func (x *ConsensusState) GetMessageRoot() []byte {
	if x != nil {
		return x.MessageRoot
	}
	return nil
}

func (x *ConsensusState) GetNextProofContextHash() []byte {
	if x != nil {
		return x.NextProofContextHash
	}
	return nil
}

type BlockUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *SignedHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *BlockUpdate) Reset() {
	*x = BlockUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_icon_lightclient_v1_light_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUpdate) ProtoMessage() {}

func (x *BlockUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_icon_lightclient_v1_light_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUpdate.ProtoReflect.Descriptor instead.
func (*BlockUpdate) Descriptor() ([]byte, []int) {
	return file_proto_icon_lightclient_v1_light_proto_rawDescGZIP(), []int{2}
}

func (x *BlockUpdate) GetHeader() *SignedHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type TrustLevel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Numerator   uint64 `protobuf:"varint,1,opt,name=numerator,proto3" json:"numerator,omitempty"`
	Denominator uint64 `protobuf:"varint,2,opt,name=denominator,proto3" json:"denominator,omitempty"`
}

func (x *TrustLevel) Reset() {
	*x = TrustLevel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_icon_lightclient_v1_light_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrustLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustLevel) ProtoMessage() {}

func (x *TrustLevel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_icon_lightclient_v1_light_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustLevel.ProtoReflect.Descriptor instead.
func (*TrustLevel) Descriptor() ([]byte, []int) {
	return file_proto_icon_lightclient_v1_light_proto_rawDescGZIP(), []int{3}
}

func (x *TrustLevel) GetNumerator() uint64 {
	if x != nil {
		return x.Numerator
	}
	return 0
}

func (x *TrustLevel) GetDenominator() uint64 {
	if x != nil {
		return x.Denominator
	}
	return 0
}

type Misbehaviour struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string       `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Header_1 *BlockUpdate `protobuf:"bytes,2,opt,name=header_1,json=header1,proto3" json:"header_1,omitempty"`
	Header_2 *BlockUpdate `protobuf:"bytes,3,opt,name=header_2,json=header2,proto3" json:"header_2,omitempty"`
}

func (x *Misbehaviour) Reset() {
	*x = Misbehaviour{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_icon_lightclient_v1_light_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Misbehaviour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Misbehaviour) ProtoMessage() {}

func (x *Misbehaviour) ProtoReflect() protoreflect.Message {
	mi := &file_proto_icon_lightclient_v1_light_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Misbehaviour.ProtoReflect.Descriptor instead.
func (*Misbehaviour) Descriptor() ([]byte, []int) {
	return file_proto_icon_lightclient_v1_light_proto_rawDescGZIP(), []int{4}
}

func (x *Misbehaviour) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Misbehaviour) GetHeader_1() *BlockUpdate {
	if x != nil {
		return x.Header_1
	}
	return nil
}

func (x *Misbehaviour) GetHeader_2() *BlockUpdate {
	if x != nil {
		return x.Header_2
	}
	return nil
}

var File_proto_icon_lightclient_v1_light_proto protoreflect.FileDescriptor

var file_proto_icon_lightclient_v1_light_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x63, 0x6f, 0x6e, 0x2f, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x69, 0x63, 0x6f, 0x6e, 0x2e, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x63, 0x6f, 0x6e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x76,
	0x31, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x95, 0x02,
	0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x27, 0x0a,
	0x0f, 0x74, 0x72, 0x75, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x72, 0x6f, 0x7a, 0x65, 0x6e,
	0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x66,
	0x72, 0x6f, 0x7a, 0x65, 0x6e, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x6d,
	0x61, 0x78, 0x5f, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x64, 0x72, 0x69, 0x66, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x6d, 0x61, 0x78, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x72,
	0x69, 0x66, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x68, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x6c, 0x61, 0x74, 0x65,
	0x73, 0x74, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x72, 0x63, 0x5f,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x73, 0x72, 0x63, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x64, 0x12, 0x26, 0x0a,
	0x0f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x54,
	0x79, 0x70, 0x65, 0x49, 0x64, 0x22, 0x6a, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73,
	0x75, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x35, 0x0a, 0x17, 0x6e, 0x65,
	0x78, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x14, 0x6e, 0x65, 0x78,
	0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x48, 0x61, 0x73,
	0x68, 0x22, 0x42, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x33, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x69, 0x63, 0x6f, 0x6e, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x4c, 0x0a, 0x0a, 0x54, 0x72, 0x75, 0x73, 0x74, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x69, 0x6e, 0x61,
	0x74, 0x6f, 0x72, 0x22, 0xa5, 0x01, 0x0a, 0x0c, 0x4d, 0x69, 0x73, 0x62, 0x65, 0x68, 0x61, 0x76,
	0x69, 0x6f, 0x75, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x3b, 0x0a, 0x08, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x31, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x69, 0x63, 0x6f, 0x6e, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x31, 0x12, 0x3b,
	0x0a, 0x08, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x69, 0x63, 0x6f, 0x6e, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x32, 0x42, 0x37, 0x0a, 0x15, 0x63,
	0x6f, 0x6d, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e,
	0x69, 0x63, 0x6f, 0x6e, 0x42, 0x0a, 0x49, 0x63, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x5a, 0x12, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x69, 0x63, 0x6f, 0x6e, 0x2f, 0x69, 0x62, 0x63, 0x3b,
	0x69, 0x63, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_icon_lightclient_v1_light_proto_rawDescOnce sync.Once
	file_proto_icon_lightclient_v1_light_proto_rawDescData = file_proto_icon_lightclient_v1_light_proto_rawDesc
)

func file_proto_icon_lightclient_v1_light_proto_rawDescGZIP() []byte {
	file_proto_icon_lightclient_v1_light_proto_rawDescOnce.Do(func() {
		file_proto_icon_lightclient_v1_light_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_icon_lightclient_v1_light_proto_rawDescData)
	})
	return file_proto_icon_lightclient_v1_light_proto_rawDescData
}

var file_proto_icon_lightclient_v1_light_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_icon_lightclient_v1_light_proto_goTypes = []interface{}{
	(*ClientState)(nil),    // 0: icon.lightclient.v1.ClientState
	(*ConsensusState)(nil), // 1: icon.lightclient.v1.ConsensusState
	(*BlockUpdate)(nil),    // 2: icon.lightclient.v1.BlockUpdate
	(*TrustLevel)(nil),     // 3: icon.lightclient.v1.TrustLevel
	(*Misbehaviour)(nil),   // 4: icon.lightclient.v1.Misbehaviour
	(*SignedHeader)(nil),   // 5: icon.types.v1.SignedHeader
}
var file_proto_icon_lightclient_v1_light_proto_depIdxs = []int32{
	5, // 0: icon.lightclient.v1.BlockUpdate.header:type_name -> icon.types.v1.SignedHeader
	2, // 1: icon.lightclient.v1.Misbehaviour.header_1:type_name -> icon.lightclient.v1.BlockUpdate
	2, // 2: icon.lightclient.v1.Misbehaviour.header_2:type_name -> icon.lightclient.v1.BlockUpdate
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_icon_lightclient_v1_light_proto_init() }
func file_proto_icon_lightclient_v1_light_proto_init() {
	if File_proto_icon_lightclient_v1_light_proto != nil {
		return
	}
	file_proto_icon_types_v1_types_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_icon_lightclient_v1_light_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_icon_lightclient_v1_light_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsensusState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_icon_lightclient_v1_light_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_icon_lightclient_v1_light_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrustLevel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_icon_lightclient_v1_light_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Misbehaviour); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_icon_lightclient_v1_light_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_icon_lightclient_v1_light_proto_goTypes,
		DependencyIndexes: file_proto_icon_lightclient_v1_light_proto_depIdxs,
		MessageInfos:      file_proto_icon_lightclient_v1_light_proto_msgTypes,
	}.Build()
	File_proto_icon_lightclient_v1_light_proto = out.File
	file_proto_icon_lightclient_v1_light_proto_rawDesc = nil
	file_proto_icon_lightclient_v1_light_proto_goTypes = nil
	file_proto_icon_lightclient_v1_light_proto_depIdxs = nil
}
